#!/bin/bash

source _common.sh

ynh_script_progression "Stopping IPTV Tunerr..."
ynh_systemctl --service="$app" --action="stop"

ynh_script_progression "Installing the pinned IPTV Tunerr release..."
ynh_setup_source --dest_dir="$install_dir" --full_replace=1
chown -R "$app:$app" "$install_dir"

ynh_script_progression "Refreshing the trusted-network rules and service configuration..."
iptvtunerr_prepare_service

ynh_script_progression "Starting IPTV Tunerr..."
ynh_systemctl --service="$app" --action="start"
iptvtunerr_register_service

ynh_script_progression "IPTV Tunerr upgrade completed"
